config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root 'homepage#index'

  scope :users do
    get '/:id', to: 'users/dashboard#show', as: :dashboard
    post '/:id/interested', to: 'interested#create', as: :create_interest
    post '/:id/study_interest', to: 'users/study_interests#create', as: :create_study_interest
    delete '/:id/study_interest', to: 'users/study_interests#delete', as: :delete_study_interest
    post '/:id/matura_results', to: 'users/matura_results#create', as: :add_matura_result
    delete '/:id/matura_results', to: 'users/matura_results#delete', as: :delete_matura_result
  end

  scope :highschools do
    get '/new', to: 'high_schools#new', as: :new_highschool
    post '/new', to: 'high_schools#create', as: :create_highschool
  end

  scope :academies do
    get '/', to: 'academies#index', as: :academies
    get '/new', to: 'academies#new', as: :new_academy
    post '/new', to: 'academies#create', as: :create_academy
    get '/:id', to: 'academies#show', as: :academy
    post '/new_opinion', to: 'academy_opinions#create', as: :create_academy_opinion
  end

  scope :fields do
    get '/', to: 'fields#index', as: :fields
    get '/new_field', to: 'fields#new', as: :new_field
    post '/new_field', to: 'fields#create', as: :create_field
    get '/new_detail', to: 'field_details#new', as: :new_detail
    post '/new_detail', to: 'field_details#create', as: :create_detail
    get '/:id', to: 'fields#show', as: :field
    post '/new_opinion', to: 'field_opinions#create', as: :create_field_opinion
  end
end

app/models/academy.rb
# frozen_string_literal: true

class Academy < ApplicationRecord
  enum academy_type: %i[university polytechnic music_academy medical_academy art_academy other]
  validates :name, :city, :academy_type, presence: true
  validates :name, uniqueness: { case_sensitive: false }
  has_many :users
  has_many :field_details
  has_many :field_of_studies, through: :field_details
  has_many :interesteds, through: :field_details
  has_many :academy_opinions
  has_many :field_opinions, through: :users

  paginates_per 5
end

app/controllers/academies_controller.rb
# frozen_string_literal: true

class AcademiesController < ApplicationController
  def index
    @academies = Academy.order(:name).page params[:page]
  end

  def show
    @academy = Academy.find(params[:id])
    @academy_opinion = AcademyOpinion.new
  end

  def new
    @academy = Academy.new
    authorize! :create, @academy
  end

  def create
    authorize! :create, @academy
    @academy = Academy.new(academy_params)
    if @academy.save
      flash[:notice] = 'Uczelnia została utworzona'
      redirect_to root_path
    else
      flash[:alert] = 'Wystąpił błąd.'
      render 'new'
    end
  end

  private

  def academy_params
    params.require(:academy).permit(:name, :city, :academy_type)
  end
end

app/views/academies/_opinion.html.haml
%article.media.opinion
  %figure.media-left
    %span.icon.is-large
      %i{class: "fas fa-#{icon} fa-3x opinion_icon"}
  .media-content
    %strong= o.user.username + '  |  ' + (o.user&.field_of_study&.name.nil? ? 'Brak informacji' : o.user.field_of_study.name)
    %br
    %p= o.body

app/views/academies/index.html.haml
= javascript_pack_tag 'academies'
.academies_list#academies
  .container{style: 'padding-top: 30px;'}
    .level
      .level-left
        .level-item
          %h1.title Uczelnie
        - if current_user&.admin?
          .level-item
            = button_to("Dodaj uczelnię", new_academy_path, class: 'button is-success', method: 'get')
      .level-right
        .level-item.has-text-centered
          %div
            %p.heading Uczelni
            %p.title
              = Academy.all.count
    .level
      .container
        - @academies.each do |academy|
          = link_to academy_path(academy.id) do
            %academy-box{':academy':academy.to_json, |
            ':fields_count':academy.field_of_studies_count, |
            ':interested_count':academy.interesteds_count }
    = paginate(@academies, class: 'pagination', method: :get)
          

app/views/academies/new.html.haml
.container{style: 'padding: 15px;'}
  %h1.title Dodaj uczelnię
  .container
    .columns
      .column.is-9
        = form_for(@academy, url: new_academy_path(@academy), remote: true, authenticity_token: true) do |f|
          .field
            = label(:name, 'Nazwa uczelni', class: 'label')
            .control
              = f.text_field :name, class: 'input'
          .field
            = label(:city, 'Miasto', class: 'label')
            .control
              = f.text_field :city, class: 'input'
          .field
            = label(:academy_type, 'Typ uczelni', class: 'label')
            .control
              .select
                = f.select(:academy_type, [['Uniwersytet', 'university'], ['Politechnika', 'polytechnic'], ['Akademia muzyczna', 'music_academy'], ['Uniwersytet Medyczny', 'medical_academy'], ['Akademia artystyczna', 'art_academy'], ['Inny', 'other']], { include_blank: true })
          .field
            .control
              = f.submit "Dodaj", class: 'button is-primary'
      .column
        %article.message.is-warning
          .message-header
            %p Info
          .message-body
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
            Tempus quis placerat ut, porta nec nulla. 
            Vestibulum rhoncus ac ex sit amet fringilla. 
            Nullam gravida purus diam, et dictum. Aenean ac, in mollis lectus. Donec sodales, 
            arcu et sollicitudin porttitor, tortor urna tempor ligula, id porttitor mi magna a neque.

app/views/academies/show.html.haml
= javascript_pack_tag 'opinion'
.academy
  .container
    .columns
      .column
        %h1.title
          = @academy.name
        %h2.subtitle
          = @academy.city
        - if current_user&.admin?
          .container
            = link_to("Dodaj kierunek do uczelni", new_detail_path({ academy_id: @academy.id }), class: 'button is-success', method: 'get')
        .is-divider
        .container{style: 'height: 700px; overflow-y: no-display; overflow-x: hidden;'}
          - @academy.field_of_studies.each do |field|
            .box.academy_field_box
              = link_to(field_path(field.id), method: :get) do
                %article.media
                  .media-left
                    %figure.image.is-64x64
                      %img{ src: image_path("fields/types/#{field.field_type.to_s}.png") }
                  .media-content
                    .columns.is-centered.is-vcentered
                      .column
                        .content
                          %span.heading.is-size-6
                            = field.name
                          %span.heading
                            = FieldOfStudy.human_enum_name(:field_type, field.field_type)
                      .column.has-text-centered
                        %span.title.is-size-7 ZAINTERESOWANI
                        %p.title.is-size-4
                          = field.interesteds_count
      .column
        .academy_photo{ style: "background-image:url(#{image_path('academies/'+@academy.id.to_s+'.jpg')})" }
        .container#opinions{ style: 'margin-top: 20px;' }
          %h2.subtitle Opinie o uczelni
          - if current_user&.student_of_academy?(@academy) || current_user&.admin?
            %button.button.is-success{ 'v-on:click':'showModal()' } Dodaj opinię
            .is-divider
            = form_for(@academy_opinion, url: create_academy_opinion_path(@academy_opinion), remote: true, authenticity_token: true) do |f|
              = render 'shared/new_opinion_form', f: f, resource: @academy
          .container{style: 'height: 700px; overflow: auto;'}
            - @academy.academy_opinions.each do |o|
              - if o.is_positive
                .notification.positive_opinion{style: 'padding: 10px;'}
                  = render 'opinion', o: o, icon: 'smile-beam'
              - else
                .notification.negative_opinion{style: 'padding: 10px;'}
                  = render 'opinion', o: o, icon: 'frown'