config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root 'homepage#index'

  scope :users do
    get '/:id', to: 'users/dashboard#show', as: :dashboard
    post '/:id/interested', to: 'interested#create', as: :create_interest
    post '/:id/study_interest', to: 'users/study_interests#create', as: :create_study_interest
    delete '/:id/study_interest', to: 'users/study_interests#delete', as: :delete_study_interest
    post '/:id/matura_results', to: 'users/matura_results#create', as: :add_matura_result
    delete '/:id/matura_results', to: 'users/matura_results#delete', as: :delete_matura_result
  end

  scope :highschools do
    get '/new', to: 'high_schools#new', as: :new_highschool
    post '/new', to: 'high_schools#create', as: :create_highschool
  end

  scope :academies do
    get '/', to: 'academies#index', as: :academies
    get '/new', to: 'academies#new', as: :new_academy
    post '/new', to: 'academies#create', as: :create_academy
    get '/:id', to: 'academies#show', as: :academy
    post '/new_opinion', to: 'academy_opinions#create', as: :create_academy_opinion
  end

  scope :fields do
    get '/', to: 'fields#index', as: :fields
    get '/new_field', to: 'fields#new', as: :new_field
    post '/new_field', to: 'fields#create', as: :create_field
    get '/new_detail', to: 'field_details#new', as: :new_detail
    post '/new_detail', to: 'field_details#create', as: :create_detail
    get '/:id', to: 'fields#show', as: :field
    post '/new_opinion', to: 'field_opinions#create', as: :create_field_opinion
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  attr_accessor :results

  enum gender: %i[female male not_specified]
  enum account_type: %i[schoolboy student partner admin]
  validates :username, :email, :encrypted_password, :account_type, presence: true
  validates :username, :email, uniqueness: { case_sensitive: false }
  has_many :matura_results
  has_many :study_interests
  has_many :matura_subjects, -> { distinct }, through: :matura_results
  has_many :field_of_studies, through: :study_interests
  has_many :field_details, through: :field_of_studies
  has_many :academy_opinions
  has_many :field_opinions
  has_many :interesteds
  belongs_to :high_school, optional: true
  belongs_to :field_of_study, optional: true
  belongs_to :academy, optional: true
  accepts_nested_attributes_for :matura_results
  accepts_nested_attributes_for :study_interests

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :encryptable

  def formulas
    field_details.collect(&:recrutation_formula)
  end

  def admin?
    account_type == 'admin'
  end

  def schoolboy?
    account_type == 'schoolboy'
  end

  def basic_results
    matura_results.select(&:basic?)
  end

  def advanced_results
    matura_results.select(&:advanced?)
  end

  def student_of_academy?(academy)
    account_type == 'student' && self.academy == academy
  end

  def student_of_field?(field_of_study)
    account_type == 'student' && self.field_of_study == field_of_study
  end

  def interested_in_field?(field)
    if field.instance_of?(FieldDetail)
      interesteds.one? { |f| f.field_detail_id == field.id }
    elsif field.instance_of?(String)
      interesteds.one? { |f| f.field_detail.field_of_study.name == field }
    end
  end
end

app/controllers/users/dashboard_controller.rb
# frozen_string_literal: true

module Users
  class DashboardController < ApplicationController
    def show
      @user = User.eager_load(:matura_results, :field_details).find(params[:id])
      authorize! :read, @user
      @fields = @user.field_details
      @formulas = @user.formulas
      @results = @user.results unless RecrutationPointsCalculator.call(@user)

      @study_interest = StudyInterest.new
      @matura_result = MaturaResult.new
    end
  end
end

app/controllers/users/matura_results_controller.rb
# frozen_string_literal: true

module Users
  class MaturaResultsController < ApplicationController
    def create
      @matura_result = MaturaResult.new(matura_results_params)
      if @matura_result.save
        flash[:notice] = 'Dodano wynik matury'
      else
        flash[:danger] = 'Coś poszło nie tak'
      end
      redirect_to dashboard_path(current_user.id)
    end

    # TODO: Bring update functionality to life
    def update
      if @matura_result.update(matura_results_params)
        flash[:notice] = 'Zaktualizowano wynik matury'
      else
        flash[:danger] = 'Coś poszło nie tak'
      end
      redirect_to dashboard_path(current_user.id)
    end

    def delete
      @matura_result = MaturaResult.find(params[:matura_result_id])
      if @matura_result.destroy
        flash[:notice] = 'Usunięto wynik matury'
      else
        flash[:danger] = 'Coś poszło nie tak'
      end
      redirect_to root_path
    end

    private

    def matura_results_params
      params.require(:matura_result).permit(:user_id, :level, :matura_subject_id, :result)
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController
    before_action :configure_sign_up_params, only: [:create]

    # GET /resource/sign_up
    def new
      @user = User.new
      @user.matura_results.build
      @user.study_interests.build
    end

    # POST /resource
    def create
      build_resource(sign_up_params)
      resource.save
      yield resource if block_given?
      if resource.persisted?
        if resource.active_for_authentication?
          set_flash_message! :notice, :signed_up
          sign_up(resource_name, resource)
        else
          set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
          expire_data_after_sign_in!
        end
      else
        clean_up_passwords resource
        set_minimum_password_length
        respond_with resource
      end
    end

    protected

    # If you have extra params to permit, append them to the sanitizer.
    def configure_sign_up_params
      devise_parameter_sanitizer.permit(:sign_up, keys:
        [:username, :email, :password, :account_type,
        :gender, :date_of_birth, :city, :high_school_id, :academy_id, :field_of_study_id, :date_of_matura, matura_results_attributes: [:id, :user_id, :matura_subject_id, :level, :result],
        study_interests_attributes: [:id, :user_id, :field_of_study_id]])
    end
  end
end

app/controllers/users/study_interests_controller.rb
# frozen_string_literal: true

module Users
  class StudyInterestsController < ApplicationController
    def create
      @study_interest = StudyInterest.new(study_interest_params)
      if @study_interest.save
        flash[:notice] = 'Dodano kierunek studiów'
      else
        flash[:danger] = 'Coś poszło nie tak'
      end
      redirect_to dashboard_path(current_user.id), method: :get
    end

    def delete
      study_interest = StudyInterest.where(user_id: study_interest_params[:user_id],
                                           field_of_study_id: study_interest_params[:field_of_study_id])

      if study_interest.destroy_all
        flash[:notice] = 'Usunięto kierunek z zainteresowań'
      else
        flash[:danger] = 'Coś poszło nie tak'
      end
      redirect_to root_path
    end

    private

    def study_interest_params
      params.require(:study_interest).permit(:user_id, :field_of_study_id)
    end
  end
end

app/views/users/dashboard/_add_matura_results_form.html.haml
.modal{'v-bind:class': "{ 'is-active': isAddingMaturaResult }"}
  .modal-background
  .modal-card
    %header.modal-card-head
      %p.modal-card-title Dodaj wynik
      %button.delete{ type: 'button', 'v-on:click':'closeAddResultForm()'}
    %section.modal-card-body
      .field
        %label.label Użytkownik
        .control
          %input.input{ disabled: true, value: current_user.username }
        = f.hidden_field :user_id, value: current_user.id
      .columns.is-variable
        .column
          .field
            .control.has-icons-left
              .select
                = f.select(:matura_subject_id, MaturaSubject.all.collect {|p| [ p.name, p.id ] })
                %span.icon.is-small.is-left
                  %i.fas.fa-chalkboard-teacher
        .column
          .control
            .select
              = f.select(:level, [['Podstawowy', 'basic'], ['Rozszerzony', 'advanced']])
        .column
          .control
            = f.number_field :result, class: 'input', min: 0, max: 100
    %footer.modal-card-foot
      %button.button.is-success{ 'v-on:click':'submitAddResultForm()' } Zapisz
      %button.button.is-danger{ type: 'button', 'v-on:click':'closeAddResultForm()' } Anuluj

app/views/users/dashboard/_add_study_interest_form.html.haml
.modal{'v-bind:class': "{ 'is-active': isAddingStudyInterests }"}
  .modal-background
  .modal-card
    %header.modal-card-head
      %p.modal-card-title Dodaj kierunek studiów
      %button.delete{ type: 'button', 'v-on:click':'closeStudyInterestForm()'}
    %section.modal-card-body
      .field
        %label.label Użytkownik
        .control
          %input.input{ disabled: true, value: current_user.username }
        = f.hidden_field :user_id, value: current_user.id
      .field
        %label.label Kierunek studiów
        .select
          = f.select(:field_of_study_id, FieldOfStudy.all.collect {|field| [field.name, field.id]})
    %footer.modal-card-foot
      %button.button.is-success{ 'v-on:click':'submitStudyInterestForm()' } Zapisz
      %button.button.is-danger{ type: 'button', 'v-on:click':'closeStudyInterestForm()' } Anuluj

app/views/users/dashboard/_admin_panel.html.haml
%h1.title Panel administracyjny
.container#admin-panel
  .tile.is-ancestor
    .tile.is-vertical.is-8
      .tile
        .tile.is-parent.is-vertical
          %article.tile.is-child.notification.is-info
            = link_to new_field_path, method: :get do
              .container
                %span.icon
                  %i.fas.fa-graduation-cap
                %p.title Dodaj kierunek studiów
          %article.tile.is-child.notification.is-success
            = link_to new_academy_path, method: :get do
              .container
                %span.icon
                  %i.fas.fa-university
                %p.title Dodaj uczelnię
        .tile.is-parent
          %article.tile.is-child.notification.is-warning
            = link_to new_detail_path, method: :get do
              .container
                %span.icon
                  %i.fas.fa-user-graduate
                %p.title Dodaj szczegóły kierunku
                %article.message.is-danger
                  .message-body
                    %p Użyj generatora do utworzenia wzoru rekrutacyjnego i upewnij się, że jest on poprawny!
      .tile.is-parent
        %article.tile.is-child.notification.is-dark
          = link_to new_highschool_path, method: :get do
            .container
              %span.icon
                %i.fas.fa-school
              %p.title Dodaj szkołę
    .tile.is-parent
      %article.tile.is-child.message.is-danger
        .message-header 
          %p Wskazówki
        .message-body
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
          Tempus quis placerat ut, porta nec nulla. 
          Vestibulum rhoncus ac ex sit amet fringilla. 
          Nullam gravida purus diam, et dictum. Aenean ac, in mollis lectus. Donec sodales, 
          arcu et sollicitudin porttitor, tortor urna tempor ligula, id porttitor mi magna a neque.

app/views/users/dashboard/_basic_statistics.html.haml
.tile.is-ancestor
  .tile.is-vertical
    .tile
      .tile.is-parent
        %article.tile.is-child.notification.is-primary.has-text-centered
          %p Użytkownicy
          %strong= User.all.count
      .tile.is-parent
        %article.tile.is-child.notification.is-primary.has-text-centered
          %p Uczelnie
          %strong= Academy.all.count
    .tile
      .tile.is-parent
        %article.tile.is-child.notification.is-primary.has-text-centered
          %p Kierunki
          %strong= FieldOfStudy.all.count
      .tile.is-parent
        %article.tile.is-child.notification.is-primary.has-text-centered
          %p Szkoły:
          %strong= HighSchool.all.count
    .tile
      .tile.is-parent
        %article.tile.is-child.notification.is-primary.has-text-centered
          %p Studenci
          %strong= User.where(account_type: 'student').count
      .tile.is-parent
        %article.tile.is-child.notification.is-primary.has-text-centered
          %p Partnerzy
          %strong= User.where(account_type: 'partner').count

app/views/users/dashboard/_report.html.haml
%h1.title Raport
.container{style:'height: 650px; overflow: auto;'}
  .tile.is-ancestor
  - @fields.each_with_index do |field, id|
    .tile.is-12.is-vertical{style: 'padding: 10px;'}
      .box#detail_box
        .columns.is-centered.is-vcentered
          .column.is-5
            %span.subtitle 
              = field.name
            %p.info
              = "#{field.academy.name} - #{field.academy.city}"
          .column
            %p.heading Limit miejsc
            - unless field.students_limit.blank?
              %p 
                = field.students_limit
            - else
              %p Brak informacji
          .column
            %p.heading Próg punktowy
            - unless field.minimal_points.blank?
              %p 
                = field.minimal_points.to_s+' pkt'
            - else
              %p Brak informacji
          .column
            %p.heading Twój wynik
            %p 
              = "#{@user.results[id]} pkt"
          - unless current_user.interested_in_field?(field)
            .column
              %p.heading Zainteresowany?
              = link_to create_interest_path(interested: { user_id: current_user.id, field_detail_id: field.id }), method: :post, class: 'button is-fullwidth is-success' do
                %span.icon.is-small
                  %i.fas.fa-check
              

app/views/users/dashboard/_user_matura_results.html.haml
%table.table.is-fullwidth
  %thead
    %tr
      %th Przedmiot
      %th Poziom
      %th Wynik
  %tbody
  - @user.matura_results.each do |mr|
    %tr
      %td 
        = mr.matura_subject.name
      %td
        = MaturaResult.human_enum_name(:level, mr.level)
      %td
        = mr.result
      %td
        = link_to delete_matura_result_path(matura_result_id: mr.id), method: :delete, class: 'button is-small is-danger' do
          %i.fas.fa-times
.button.is-primary{'v-on:click':'showAddResultForm()'} Dodaj wynik
= form_for(@matura_result, url: add_matura_result_path(@matura_result, id: current_user.id), method: :post, authenticity_token: true) do |f|
  = render 'add_matura_results_form', f: f

app/views/users/dashboard/show.html.haml
= javascript_pack_tag 'user_dashboard'
.dashboard#user-dashboard
  .container{style: 'padding: 25px;'}
    .columns
      .column.is-4
        .columns.is-centered.is-vcentered
          .column
            %h2.title
              = @user.username
            %h2.subtitle 
              = @user.email
        .column
          .list
            - @user.field_of_studies.each do |field|
              %li.list-item
                = field.name
                .container.is-pulled-right
                  = link_to delete_study_interest_path(study_interest: { user_id: @user, field_of_study_id: field}), method: :delete, class: 'button is-small is-danger' do
                    %i.fas.fa-times
          - if @user.study_interests.count < 5
            .button.is-primary{'v-on:click':'showStudyInterestForm'} Dodaj kierunki studiów
            = form_for(@study_interest, url: create_study_interest_path(@study_interest, id: current_user.id), method: :post, remote: true, authenticity_token: true) do |f|
              = render 'add_study_interest_form', f: f
        .container
          - if current_user.schoolboy?
            = render 'user_matura_results'
          - elsif current_user.admin?
            = render 'basic_statistics'
      .column
        - if current_user.schoolboy?
          = render 'report'
        - elsif current_user.admin?
          = render 'admin_panel'