config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root 'homepage#index'

  scope :users do
    get '/:id', to: 'users/dashboard#show', as: :dashboard
    post '/:id/interested', to: 'interested#create', as: :create_interest
    post '/:id/study_interest', to: 'users/study_interests#create', as: :create_study_interest
    delete '/:id/study_interest', to: 'users/study_interests#delete', as: :delete_study_interest
    post '/:id/matura_results', to: 'users/matura_results#create', as: :add_matura_result
    delete '/:id/matura_results', to: 'users/matura_results#delete', as: :delete_matura_result
  end

  scope :highschools do
    get '/new', to: 'high_schools#new', as: :new_highschool
    post '/new', to: 'high_schools#create', as: :create_highschool
  end

  scope :academies do
    get '/', to: 'academies#index', as: :academies
    get '/new', to: 'academies#new', as: :new_academy
    post '/new', to: 'academies#create', as: :create_academy
    get '/:id', to: 'academies#show', as: :academy
    post '/new_opinion', to: 'academy_opinions#create', as: :create_academy_opinion
  end

  scope :fields do
    get '/', to: 'fields#index', as: :fields
    get '/new_field', to: 'fields#new', as: :new_field
    post '/new_field', to: 'fields#create', as: :create_field
    get '/new_detail', to: 'field_details#new', as: :new_detail
    post '/new_detail', to: 'field_details#create', as: :create_detail
    get '/:id', to: 'fields#show', as: :field
    post '/new_opinion', to: 'field_opinions#create', as: :create_field_opinion
  end
end

app/controllers/fields_controller.rb
# frozen_string_literal: true

class FieldsController < ApplicationController
  def index
    @all_fields = FieldOfStudy.all
    @fields = FieldOfStudy.order(:name).page params[:page]
  end

  def show
    @field = FieldOfStudy.find(params[:id])
    @field_opinion = FieldOpinion.new
  end

  def new
    @field_of_study = FieldOfStudy.new
    authorize! :create, @field
  end

  def create
    @field_of_study = FieldOfStudy.new(field_of_study_params)
    authorize! :create, @field_of_study
    if @field_of_study.save
      flash[:notice] = 'Kierunek został utworzony'
      redirect_to root_path
    else
      flash[:alert] = 'Coś poszło nie tak'
      render 'new'
    end
  end

  private

  def field_of_study_params
    params.require(:field_of_study).permit(:name, :field_type)
  end
end

app/views/fields/_opinion.html.haml
%article.media.opinion
  %figure.media-left
    %span.icon.is-large
      %icon{class: "fas fa-#{icon} fa-3x opinion_icon"}
  .media-content
    %strong= o.user.username + '  |  ' + (o.user&.academy&.name.nil? ? 'Brak informacji' : o.user.academy.name)
    %br
    %p= o.body

app/views/fields/index.html.haml
= javascript_pack_tag 'fields'
.fields_list#fields
  .container{style: 'padding-top: 30px;'}
    .level
      .level-left
        %h1.title Kierunki
        - if current_user && current_user.account_type == 'admin'
          .level-item
            = button_to("Dodaj kierunek", new_field_path, class: 'button is-success', method: 'get')
      .level-right
        .level-item.has-text-centered
          %div
            %p.heading Kierunków
            %p.title
              = @all_fields.count
    .level
      .container
        - @fields.each do |field|
          = link_to field_path(field.id) do
            %field-box{':field':{ |
              'id':field.id, |
              'name':field.name, |
              'type_enum':field.field_type, |
              'type':FieldOfStudy.human_enum_name(:field_type, field.field_type), |
              'academies_count':field.academies_count, |
              'interested_count':field.interesteds_count }.to_json }
    = paginate(@fields, class: 'pagination')
          

app/views/fields/new.html.haml
.container{style: 'padding: 15px;'}
  %h1.title Dodaj kierunek
  .container
    .columns
      .column.is-9
        = form_for(@field_of_study, url: new_field_path(@field_of_study), remote: true, authenticity_token: true) do |f|
          .field
            = label(:name, 'Nazwa kierunku', class: 'label')
            .control
              = f.text_field :name, class: 'input'
          .field
            = label(:field_type, 'Typ kierunku', class: 'label')
            .control
              .select
                = f.select(:field_type, [['Humanistyczny', 'humanities'], ['Administracyjny', 'administrative'], ['Artystyczny', 'artistic'], ['Medyczny', 'medical'], ['Społeczny', 'social_sciences'], ['Nauki przyrodnicze', 'natural_sciences'], ['Nauki ścisłe', 'formal_sciences'], ['Nauki techniczne', 'technical'], ['Wychowanie fizyczne', 'sports'], ['Filologiczny', 'linguistic'], ['Ekonomiczny', 'economical'], ['Pedagogiczny', 'pedagogical'], ['Prawniczy', 'law'], ['Psychologiczny', 'psychological'], ['Wojskowy', 'military'], ['Rolniczy', 'agricultural'], ['Inny', 'others']], { include_blank: true })
          .field
            .control
              = f.submit "Dodaj", class: 'button is-primary'
      .column
        %article.message.is-warning
          .message-header
            %p Info
          .message-body
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
            Tempus quis placerat ut, porta nec nulla. 
            Vestibulum rhoncus ac ex sit amet fringilla. 
            Nullam gravida purus diam, et dictum. Aenean ac, in mollis lectus. Donec sodales, 
            arcu et sollicitudin porttitor, tortor urna tempor ligula, id porttitor mi magna a neque.

app/views/fields/show.html.haml
= javascript_pack_tag 'opinion'
.field_container
  .container
    .columns
      .column.is-8
        %h1.title
          = @field.name
        %h2.subtitle
          = FieldOfStudy.human_enum_name(:field_type, @field.field_type)
        %figure.image
          .field_photo{ style: "background-image:url(#{image_path('fields/'+@field.id.to_s+'.jpg')})" }
        .container{style: 'margin-top: 20px;'}
        .is-divider
        .columns
          .column
            .container
              %p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
          .column
            .container
            - if current_user && current_user.account_type == 'admin'
              .container{style: 'margin-bottom: 10px;'}
                = link_to("Przypisz uczelnię", new_detail_path({ field_id: @field.id }), class: 'button is-success', method: 'get')
            - @field.academies.each do |academy|
              .box.field_academy_box
                = link_to(academy_path(academy.id), method: :get) do
                  %article.media
                    %figure.media-left
                      %p.image.is-64x64
                        %image{src:"#{image_path("cities/"+academy.city.to_s.downcase+".png")}"}
                    .media-content
                      .columns.is-centered.is-vcentered
                        .column.has-text-left
                          .content
                            %span.heading.is-size-6
                              = academy.name
                            %span.heading.is-size-7
                              = academy.city
                        .column.has-text-centered
                          %span.title.is-size-6 Zainteresowani
                          %p.title.is-size-5= academy.interesteds_count
      .column#opinions
        %h2.subtitle Opinie o kierunku
        - if current_user&.student_of_field?(@field) || current_user&.admin?
          %button.button.is-success{ 'v-on:click':'showModal()' } Dodaj opinię
          .is-divider
          = form_for(@field_opinion, url: create_field_opinion_path(@field_opinion), remote: true, authenticity_token: true) do |f|
            = render 'shared/new_opinion_form', f: f, resource: @field
        .container{style: 'height: 400px; overflow: auto;'}
          - @field.field_opinions.each do |o|
            - if o.is_positive
              .notification.positive_opinion{style: 'padding: 10px;'}
                = render 'opinion', o: o, icon: 'smile-beam'
            - else
              .notification.negative_opinion{style: 'padding: 10px;'}
                = render 'opinion', o: o, icon: 'frown'
        .container{style: 'padding: 10px;'}
          .soon
          .content.wip
            %h2.subtitle Przedmioty maturalne
            %table.table.is-fullwidth
              %thead
                %tr
                  %th Przedmiot
                  %th Procent uczelni wliczających
              %tbody
                - 3.times do
                  %tr
                    %td
                      Przedmiot
                    %td
                      Procenty
              