config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root 'homepage#index'

  scope :users do
    get '/:id', to: 'users/dashboard#show', as: :dashboard
    post '/:id/interested', to: 'interested#create', as: :create_interest
    post '/:id/study_interest', to: 'users/study_interests#create', as: :create_study_interest
    delete '/:id/study_interest', to: 'users/study_interests#delete', as: :delete_study_interest
    post '/:id/matura_results', to: 'users/matura_results#create', as: :add_matura_result
    delete '/:id/matura_results', to: 'users/matura_results#delete', as: :delete_matura_result
  end

  scope :highschools do
    get '/new', to: 'high_schools#new', as: :new_highschool
    post '/new', to: 'high_schools#create', as: :create_highschool
  end

  scope :academies do
    get '/', to: 'academies#index', as: :academies
    get '/new', to: 'academies#new', as: :new_academy
    post '/new', to: 'academies#create', as: :create_academy
    get '/:id', to: 'academies#show', as: :academy
    post '/new_opinion', to: 'academy_opinions#create', as: :create_academy_opinion
  end

  scope :fields do
    get '/', to: 'fields#index', as: :fields
    get '/new_field', to: 'fields#new', as: :new_field
    post '/new_field', to: 'fields#create', as: :create_field
    get '/new_detail', to: 'field_details#new', as: :new_detail
    post '/new_detail', to: 'field_details#create', as: :create_detail
    get '/:id', to: 'fields#show', as: :field
    post '/new_opinion', to: 'field_opinions#create', as: :create_field_opinion
  end
end

app/views/layouts/_footer.html.haml
%footer.footer
  = debug(params) if Rails.env.development?
  .content.has-text-centered
    %p
      %strong HighSchooler
      Copyright &copy; by Krzysztof Janiec 2019

app/views/layouts/_navigation.html.haml
%nav.navbar{role: "navigation"}
  .container.is-fluid
    .navbar-brand
      = link_to image_tag("logo_xs.png", size: '110x51', style: 'padding: 5px'), root_path
    .navbar-menu
      .navbar-end
        = link_to 'Uczelnie', academies_path , class: 'navbar-item', method: :get
        = link_to 'Kierunki', fields_path , class: 'navbar-item', method: :get
        - if user_signed_in?
          = link_to 'Wyloguj', destroy_user_session_path, class: 'navbar-item'
        - else
          = link_to 'Zaloguj', new_user_session_path, class: 'navbar-item'
          = link_to 'Zarejestruj', new_user_registration_path, method: :get, class: 'navbar-item register_button'

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Highschooler
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/navigation'
    .app-content
      - if notice
        .container.is-fluid.notification-box
          .notification.is-info
            = notice
      - if alert
        .container.is-fluid.notification-box
          .notification.is-danger
            = alert
      = yield
    = render 'layouts/footer'